package com.example.adarshindia.model

import androidx.room.Ignore

data class ApiRequest(
    var user_id : String = "",
    var mobile_no : String = "",
    var mobile_number : String = "",
    var full_name : String = "",
    var gender : String = "",
    var device_id : String = "",
    var android_token : String = "",
    var device_model : String = "",
    var device_os_version : String = "",
    var state_id : String = "",
    var otp : String = "",
    var from : String = "",
    var city_id : String ="",
    var pin_code : String ="",
    var address_type : String = "",
    var loan_amount : String = "",
    var reason_for : String = "",
    var mpin : String = "",
    var any_running_loan : String = "",
    var first_name : String = "",
    var last_name : String = "",
    var father_first_name : String = "",
    var father_last_name : String = "",
    var father_occupation : String = "",
    var email : String = "",
    var dob : String = "",
    var kyc_id : String = "",
    var alternet_mobile_no : String = "",
    var guardian_first_name : String = "",
    var guardian_last_name : String = "",
    var guardian_mobile_no : String = "",
    var guardian_relationship : String = "",
    var occupation : String = "",
    var monthly_income : String = "",
    var family_members : String = "",
    var who_are_in_family : String = "",
    var address_proof_type : String = "",
    var address_proof : String = "",
    var aadhar_no : String = "",
    var pan_no : String = "",
    var bank_ac_no : String = "",
    var ifsc_code : String = "",
    var bank_name : String = "",
    var voter_id_no : String = "",
    var aadhar_front_pic : String = "",
    var aadhar_back_pic : String = "",
    var pan_card_pic : String = "",
    var passbook_photo : String = "",
    var voter_id_front_pic : String = "",
    var voter_id_back_pic : String = "",
    var passport_photo : String = "",
    var amount : String = "",
    var payment_id : String = "",
    var transaction_date : String = "",
    var status : String = "",
)
