package com.example.adarshindia.model

data class Records(
    val android_token: String,
    val city_id: Any,
    val created_at: String,
    val device_id: String,
    val device_model: String,
    val device_os_version: String,
    val dob: Any,
    val email: Any,
    val first_name: Any,
    val full_name: String,
    var image : String,
    val gender: String,
    val id: String,
    val is_mobile_verified: String,
    val language: Any,
    val last_name: Any,
    val marital_status: Any,
    val mobile_no: String,
    val name : String,
    val otp: String,
    val profile_pic: Any,
    val qualifications: Any,
    val state_id: String,
    val status: String,
    val kyc_id: String,
    val address_type: String,
    val address_proof_type: String,
    val pin_code: String,
    val kyc_address_id: String,
    val is_kyc_applied: Boolean,
    val kyc_status: String,
    val is_set_mpin: Boolean,
    val donation_status: String,
    val kyc_doc_status: String,
    val kyc_address_status: String,
)